# Generated by Django 4.1.4 on 2023-02-06 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_administator_emp_id_alter_employee_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administator',
            name='emp_id',
            field=models.CharField(default='ADMIN477751', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='EMP646680', max_length=20),
        ),
        migrations.AlterField(
            model_name='hr',
            name='emp_id',
            field=models.CharField(default='HR609149', max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='emp_id',
            field=models.CharField(default='MAN952470', max_length=20),
        ),
        migrations.CreateModel(
            name='leaverequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leave_type', models.CharField(max_length=50)),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('unapproved', 'UNAPPROVED'), ('decline', 'DECLINED')], default='PENDING..', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.employee')),
            ],
        ),
    ]
