# Generated by Django 4.1.4 on 2023-02-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_administator_emp_id_alter_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='administator',
            name='emp_id',
            field=models.CharField(default='ADMIN967639', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='EMP201992', max_length=20),
        ),
        migrations.AlterField(
            model_name='hr',
            name='emp_id',
            field=models.CharField(default='HR297363', max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='emp_id',
            field=models.CharField(default='MAN190719', max_length=20),
        ),
    ]
