# Generated by Django 4.1.4 on 2023-02-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_leaverequest_status_leaverequest_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='administator',
            name='emp_id',
            field=models.CharField(default='ADMIN518204', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='EMP208465', max_length=20),
        ),
        migrations.AlterField(
            model_name='hr',
            name='emp_id',
            field=models.CharField(default='HR193731', max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='emp_id',
            field=models.CharField(default='MAN507823', max_length=20),
        ),
    ]
